name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    
    - uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    
    - name: make
      run: make nolimit_all
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: tinyfecbin
        file: tinyfecvpn
