name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: linux
    steps:
    - uses: actions/checkout@v1
    
    - uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    
    - name: make
      run: make nolimit_all
